ARTISTS = [
    {
        "name": "Frida Kahlo",
        "years": "1907–1954",
        "nacionalidad": "Mexicana",
        "movimientos": ["Surrealismo", "Arte popular mexicano"],
        "descripcion": "Pintora icónica que exploró el dolor físico, la identidad y la sexualidad en autorretratos intensamente personales. Vivió abiertamente su bisexualidad y desafió las normas de género en una época profundamente conservadora.",
        "obras_destacadas": ["Las dos Fridas (1939)", "La columna rota (1944)", "Autorretrato con collar de espinas (1940)"],
        "temas": ["identidad", "dolor", "bisexualidad", "cuerpo", "México"],
    },
    {
        "name": "Zanele Muholi",
        "years": "1972–presente",
        "nacionalidad": "Sudafricana",
        "movimientos": ["Fotografía activista", "Arte queer negro"],
        "descripcion": "Artista visual y activista que documenta y celebra las vidas de personas LGBTQ+ negras en Sudáfrica, creando un archivo visual de resistencia contra la homofobia y el racismo.",
        "obras_destacadas": ["Serie Faces and Phases", "Somnyama Ngonyama (2018)", "Serie Brave Beauties"],
        "temas": ["identidad queer negra", "activismo", "visibilidad", "raza", "género"],
    },
    {
        "name": "Claude Cahun",
        "years": "1894–1954",
        "nacionalidad": "Francesa",
        "movimientos": ["Surrealismo", "Fotografía experimental"],
        "descripcion": "Artista y escritora surrealista que exploró la fluidez de género e identidad décadas antes de que existiera el vocabulario para describirlo. Usó la fotografía para subvertir los roles de género.",
        "obras_destacadas": ["Autoportrait (1927)", "I extend my arms (1931)", "Ne m'embrassez pas (1920s)"],
        "temas": ["género fluido", "identidad", "autorretratos", "surrealismo", "transgresión"],
    },
    {
        "name": "Judy Chicago",
        "years": "1939–presente",
        "nacionalidad": "Estadounidense",
        "movimientos": ["Arte feminista", "Arte conceptual"],
        "descripcion": "Pionera del arte feminista, creadora de 'The Dinner Party', instalación monumental que celebra los logros de mujeres a lo largo de la historia occidental.",
        "obras_destacadas": ["The Dinner Party (1979)", "The Holocaust Project (1993)", "Birth Project (1985)"],
        "temas": ["historia femenina", "iconografía vaginal", "colectividad", "feminismo radical"],
    },
    {
        "name": "Ana Mendieta",
        "years": "1948–1985",
        "nacionalidad": "Cubana-estadounidense",
        "movimientos": ["Arte corporal", "Land art", "Performance"],
        "descripcion": "Artista cuyo trabajo explora la conexión entre el cuerpo femenino, la tierra, la violencia y el exilio. Su serie 'Silueta' imprime su figura en la naturaleza.",
        "obras_destacadas": ["Serie Silueta (1973–1980)", "Rastros corporales", "Árbol de la vida"],
        "temas": ["cuerpo", "tierra", "exilio", "violencia", "identidad latina"],
    },
    {
        "name": "Barbara Kruger",
        "years": "1945–presente",
        "nacionalidad": "Estadounidense",
        "movimientos": ["Arte conceptual", "Apropiacionismo"],
        "descripcion": "Artista que usa tipografía en rojo y blanco sobre imágenes en blanco y negro para cuestionar el poder, el género y el consumismo con frases que se volvieron parte de la cultura popular.",
        "obras_destacadas": ["Your body is a battleground (1989)", "We don't need another hero (1987)", "I shop therefore I am (1987)"],
        "temas": ["poder", "género", "consumismo", "mirada masculina", "política"],
    },
    {
        "name": "Louise Bourgeois",
        "years": "1911–2010",
        "nacionalidad": "Franco-estadounidense",
        "movimientos": ["Surrealismo", "Escultura contemporánea"],
        "descripcion": "Escultora cuyos trabajos monumentales exploran temas de familia, maternidad, sexualidad y trauma. Sus arañas gigantes 'Maman' se volvieron íconos del arte contemporáneo.",
        "obras_destacadas": ["Maman (1999)", "The Destruction of the Father (1974)", "Spider (1997)"],
        "temas": ["maternidad", "trauma", "sexualidad", "familia", "inconsciente"],
    },
    {
        "name": "Nan Goldin",
        "years": "1953–presente",
        "nacionalidad": "Estadounidense",
        "movimientos": ["Fotografía íntima", "Arte queer"],
        "descripcion": "Fotógrafa que documentó con crudeza la vida de su comunidad: artistas, drag queens y personas queer en Nueva York durante los años 80, incluyendo la devastación de la epidemia de SIDA.",
        "obras_destacadas": ["The Ballad of Sexual Dependency (1986)", "The Other Side (1992–2019)", "Cookie Mueller (1985)"],
        "temas": ["queer", "SIDA", "intimidad", "drogadicción", "comunidad"],
    },
    {
        "name": "Hannah Höch",
        "years": "1889–1978",
        "nacionalidad": "Alemana",
        "movimientos": ["Dadaísmo", "Nueva Objetividad"],
        "descripcion": "Artista dadaísta pionera del fotomontaje cuya obra critica el rol de la mujer en la República de Weimar y celebra abiertamente el amor entre mujeres.",
        "obras_destacadas": ["Corte con el cuchillo Dada (1919)", "Madre (1930)", "Serie 'Desde un museo etnográfico' (1924–1934)"],
        "temas": ["género", "bisexualidad", "crítica social", "fotomontaje", "Dadaísmo"],
    },
    {
        "name": "Félix González-Torres",
        "years": "1957–1996",
        "nacionalidad": "Cubano-estadounidense",
        "movimientos": ["Arte conceptual", "Minimalismo"],
        "descripcion": "Artista queer cuya obra poética y minimalista aborda el amor, la pérdida, la epidemia del SIDA y la política. Falleció de complicaciones relacionadas con el VIH.",
        "obras_destacadas": ["Untitled (Perfect Lovers) (1991)", "Untitled (Portrait of Ross) (1991)", "Untitled (Blood) (1992)"],
        "temas": ["amor gay", "SIDA", "pérdida", "política", "memoria"],
    },
    {
        "name": "Kara Walker",
        "years": "1969–presente",
        "nacionalidad": "Estadounidense",
        "movimientos": ["Arte contemporáneo", "Arte afroamericano"],
        "descripcion": "Artista conocida por sus siluetas en negro sobre blanco que exploran la historia de la esclavitud, el racismo y el género en EE.UU. con una mirada cruda e incómoda.",
        "obras_destacadas": ["Gone: An Historical Romance... (1994)", "A Subtlety (2014)", "The Kara Walker Fountain (2021)"],
        "temas": ["racismo", "esclavitud", "género", "historia", "violencia"],
    },
    {
        "name": "Cindy Sherman",
        "years": "1954–presente",
        "nacionalidad": "Estadounidense",
        "movimientos": ["Apropiacionismo", "Fotografía conceptual"],
        "descripcion": "Fotógrafa que se convierte en sus propios sujetos para explorar los estereotipos femeninos, los roles de género y la construcción de la identidad en los medios de masas.",
        "obras_destacadas": ["Untitled Film Stills (1977–1980)", "Centerfolds (1981)", "Sex Pictures (1992)"],
        "temas": ["estereotipos femeninos", "identidad", "medios", "mirada masculina", "representación"],
    },
    {
        "name": "Guerrilla Girls",
        "years": "1985–presente",
        "nacionalidad": "Colectivo anónimo, EE.UU.",
        "movimientos": ["Arte feminista", "Activismo"],
        "descripcion": "Colectivo anónimo de artistas feministas que usan máscaras de gorila y estadísticas para denunciar el sexismo y el racismo en el mundo del arte institucional.",
        "obras_destacadas": ["Do women have to be naked to get into the Met? (1989)", "The Advantages of Being a Woman Artist (1988)"],
        "temas": ["sexismo institucional", "arte y poder", "anonimato", "humor político"],
    },
    {
        "name": "Faith Ringgold",
        "years": "1930–presente",
        "nacionalidad": "Estadounidense",
        "movimientos": ["Arte afroamericano", "Arte feminista"],
        "descripcion": "Artista y escritora que usa colchas bordadas (story quilts) para narrar la historia afroamericana desde perspectivas femeninas, combinando texto e imagen.",
        "obras_destacadas": ["Tar Beach (1988)", "American People Series (1963–1967)", "Dancing at the Louvre (1991)"],
        "temas": ["raza", "género", "historia negra", "textil", "narración"],
    },
    {
        "name": "Leonora Carrington",
        "years": "1917–2011",
        "nacionalidad": "Británico-mexicana",
        "movimientos": ["Surrealismo"],
        "descripcion": "Pintora y escritora surrealista cuya obra crea mundos fantásticos habitados por brujas, animales y figuras femeninas poderosas que subvierten el surrealismo masculino.",
        "obras_destacadas": ["La Posada del Caballero del Alba (1945)", "El jardín de Paracelsus (1957)", "Autopsy (1957)"],
        "temas": ["surrealismo femenino", "magia", "alquimia", "subversión", "fantasía"],
    },
    {
        "name": "Yayoi Kusama",
        "years": "1929–presente",
        "nacionalidad": "Japonesa",
        "movimientos": ["Arte conceptual", "Pop Art", "Arte feminista"],
        "descripcion": "Artista visionaria cuyas instalaciones con lunares y espejos exploran la infinitud, la obsesión y el autoborramiento. Pionera del arte de instalación que vivió décadas en un hospital psiquiátrico.",
        "obras_destacadas": ["Infinity Mirror Rooms (desde 1965)", "Pumpkin (1994)", "Dots Obsession (1998)"],
        "temas": ["obsesión", "infinitud", "autoborramiento", "feminismo", "salud mental"],
    },
    {
        "name": "Jenny Holzer",
        "years": "1950–presente",
        "nacionalidad": "Estadounidense",
        "movimientos": ["Arte conceptual", "Arte público"],
        "descripcion": "Artista que utiliza el lenguaje como forma de arte, proyectando frases provocadoras sobre edificios y espacio público para cuestionar el poder, la violencia y el consumismo.",
        "obras_destacadas": ["Truisms (desde 1977)", "Protect Me From What I Want (1985)", "RAPE IS (1983)"],
        "temas": ["lenguaje", "poder", "violencia de género", "consumismo", "arte público"],
    },
    {
        "name": "Catherine Opie",
        "years": "1961–presente",
        "nacionalidad": "Estadounidense",
        "movimientos": ["Fotografía documental", "Arte queer"],
        "descripcion": "Fotógrafa que documenta comunidades LGBTQ+, familias queer y el paisaje americano con una mirada que interroga la pertenencia, la identidad y la comunidad.",
        "obras_destacadas": ["Being and Having (1991)", "Portraits (1993–1997)", "Surfers (2003)"],
        "temas": ["comunidad queer", "identidad lesbiana", "familia", "pertenencia", "cuerpo"],
    },
    {
        "name": "Elizabeth Catlett",
        "years": "1915–2012",
        "nacionalidad": "Afroestadounidense / Mexicana",
        "movimientos": ["Arte social", "Grabado", "Escultura"],
        "descripcion": "Escultora y grabadora cuya obra celebra la fortaleza de las mujeres negras y la lucha por los derechos civiles, con raíces en las tradiciones artísticas de EE.UU. y México.",
        "obras_destacadas": ["The Negro Woman (1946–1947)", "Mother and Child (1940)", "Sharecropper (1952)"],
        "temas": ["mujeres negras", "resistencia", "maternidad", "derechos civiles", "interseccionalidad"],
    },
    {
        "name": "Remedios Varo",
        "years": "1908–1963",
        "nacionalidad": "Española-mexicana",
        "movimientos": ["Surrealismo"],
        "descripcion": "Pintora surrealista cuyas obras crean universos fantásticos con figuras femeninas como científicas, viajeras y exploradoras autónomas, subvirtiendo el rol pasivo de la mujer en el surrealismo.",
        "obras_destacadas": ["Bordando el manto terrestre (1961)", "Exploración de las fuentes del río Orinoco (1959)", "Naturaleza muerta resucitando (1963)"],
        "temas": ["surrealismo femenino", "ciencia", "magia", "autonomía femenina", "simbolismo"],
    },
]
